### ISSUE TITLE
Cannot get started, ho pass Values to the driver

### ISSUE THREAD

**Issue by pos-ei-don** [arrow1800/Victron-VirtualBattery#1]
Hi!
Wanted to try your driver. installed it and the nodered-Flow,
butthere it is not documented how to paas the values to the rest-api http url you are using to comunicate.
Can you help here?

**Comment by arrow1800** [comment]
hi Poseidon, yes off course.  do you want to know how the values are send from node-red to the driver?

**Comment by arrow1800** [comment]
i added some extra info to the readme. does that help?

**Comment by pos-ei-don** [comment]
Thank you a lot, but sorry, it does not help me.
How can I set Charge current to 150A? How do I calll this restservice?

**Comment by arrow1800** [comment]
restservice is called by the driver. you dont have to do that.

setting charge current can be done here: 
![image](https://user-images.githubusercontent.com/12893401/212148226-806ff28e-d758-4a00-8781-af526a97c939.png)

**Comment by pos-ei-don** [comment]
This I understand. But what is at the right. Where does the payload "Flow to"

**Comment by arrow1800** [comment]
i am using node-red flow variables. these are variables that are held in memory and are available through the whole flow. in other words. they can be retrieved at another place, for example here:

![image](https://user-images.githubusercontent.com/12893401/212159017-b3c06876-1de3-4cf4-bbea-6b3831f66500.png)


more info on flow variables: https://nodered.org/docs/user-guide/context

**Comment by arrow1800** [comment]
i updated the example flow a bit more. maybe that clears things up a bit
