### ISSUE TITLE
CVL, CCL, DCL are not assigned

### ISSUE THREAD

**Issue by teefixx** [arrow1800/Victron-VirtualBattery#3]
Hi

I implemented your driver and in general it is working well. 
Unfortunately ChargeVoltageLimit, ChargeCurrentLimit and DischargeCurrentLimit are not assigned to the virtual battery in my Pi3.

In Nodered all is assigned (last node debug before the http response node)

My system:
pi3b
VenusOS 3.00-20
<img width="329" alt="image" src="https://user-images.githubusercontent.com/35899354/222184625-b3c1b55d-b35b-4d71-af5f-62e06ad351b7.png">

Any suggestions would be great.

Thank you

**Comment by teefixx** [comment]
could solve it

commented out "NrOfModulesBlockingCharge", as there was an error and I don't fill the variable.
After that CVL, CCL and DCL appeared on the venus.

**Comment by arrow1800** [comment]
hi, sorry. did not notice your message sooner. good that it is fixed. i will change the code as well
